"""
dashboard/app.py
----------------
AQI Monitoring Dashboard built with Streamlit and Plotly.
Displays current conditions, historical trends, and a 3-day AQI forecast
generated by the trained model loaded from the Hopsworks Model Registry.
"""

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import numpy as np
from pathlib import Path
from datetime import datetime, timedelta

# ---------------------------------------------------------------------------
# Page configuration
# ---------------------------------------------------------------------------

st.set_page_config(
    page_title="AQI Forecast Dashboard",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------------
# Custom CSS
# ---------------------------------------------------------------------------

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&family=IBM+Plex+Sans:wght@300;400;600&display=swap');

html, body, [class*="css"] {
    font-family: 'IBM Plex Sans', sans-serif;
    background-color: #0d0f14;
    color: #e2e8f0;
}
.stApp { background-color: #0d0f14; }

section[data-testid="stSidebar"] {
    background-color: #111318;
    border-right: 1px solid #1e2330;
}
[data-testid="metric-container"] {
    background-color: #111827;
    border: 1px solid #1e2330;
    border-radius: 8px;
    padding: 16px 20px;
}
[data-testid="metric-container"] label {
    font-family: 'IBM Plex Mono', monospace;
    font-size: 11px;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    color: #64748b;
}
[data-testid="metric-container"] [data-testid="stMetricValue"] {
    font-family: 'IBM Plex Mono', monospace;
    font-size: 26px;
    font-weight: 600;
    color: #f1f5f9;
}
.section-label {
    font-family: 'IBM Plex Mono', monospace;
    font-size: 10px;
    letter-spacing: 0.15em;
    text-transform: uppercase;
    color: #475569;
    margin-bottom: 12px;
    padding-bottom: 6px;
    border-bottom: 1px solid #1e2330;
}
.forecast-card {
    background: #111827;
    border: 1px solid #1e2330;
    border-radius: 10px;
    padding: 20px 24px;
    text-align: center;
}
.forecast-label {
    font-family: 'IBM Plex Mono', monospace;
    font-size: 10px;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: #475569;
    margin-bottom: 6px;
}
.forecast-value {
    font-family: 'IBM Plex Mono', monospace;
    font-size: 32px;
    font-weight: 600;
    color: #38bdf8;
}
.forecast-category {
    font-size: 12px;
    margin-top: 4px;
}
.aqi-badge {
    display: inline-block;
    padding: 4px 12px;
    border-radius: 4px;
    font-family: 'IBM Plex Mono', monospace;
    font-size: 12px;
    font-weight: 600;
    letter-spacing: 0.05em;
}
hr { border-color: #1e2330; margin: 24px 0; }
h1 { font-family: 'IBM Plex Sans', sans-serif; font-weight: 300; font-size: 22px; color: #f1f5f9; }
h2, h3 { font-family: 'IBM Plex Sans', sans-serif; font-weight: 400; color: #cbd5e1; }
</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

PLOT_LAYOUT = dict(
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
    font=dict(family="IBM Plex Mono", color="#64748b", size=11),
    xaxis=dict(gridcolor="#1e2330", linecolor="#1e2330", tickfont=dict(size=10)),
    yaxis=dict(gridcolor="#1e2330", linecolor="#1e2330", tickfont=dict(size=10)),
    margin=dict(l=12, r=12, t=36, b=12),
    hovermode="x unified",
)


def classify_aqi(value):
    try:
        value = float(value)
    except (TypeError, ValueError):
        return "Unknown", "#64748b"
    if value <= 50:   return "Good",                              "#22c55e"
    if value <= 100:  return "Moderate",                          "#eab308"
    if value <= 150:  return "Unhealthy for Sensitive Groups",    "#f97316"
    if value <= 200:  return "Unhealthy",                         "#ef4444"
    if value <= 300:  return "Very Unhealthy",                    "#a855f7"
    return                   "Hazardous",                         "#991b1b"


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

current_file = Path(__file__).resolve()
project_root = current_file.parent.parent

CSV_PATHS = [
    project_root / "kandhkot_aqi_data.csv",
    project_root / "data" / "kandhkot_aqi_data.csv",
    project_root / "feature_pipeline" / "kandhkot_aqi_data.csv",
    current_file.parent / "kandhkot_aqi_data.csv",
]


def load_csv_data():
    for path in CSV_PATHS:
        if path.exists():
            try:
                return pd.read_csv(path), path.name
            except Exception:
                pass
    return None, None


def generate_fallback_data(n: int = 120) -> pd.DataFrame:
    dates = pd.date_range(end=pd.Timestamp.now(), periods=n, freq="H")
    np.random.seed(42)
    base = 120 + 30 * np.sin(np.linspace(0, 4 * np.pi, n))
    return pd.DataFrame({
        "timestamp":   dates,
        "aqi":         np.clip(base + np.random.normal(0, 8, n), 50, 220).round(1),
        "temperature": np.random.uniform(28, 44, n).round(1),
        "humidity":    np.random.uniform(35, 72, n).round(1),
        "pm25":        np.random.uniform(35, 90, n).round(1),
        "pm10":        np.random.uniform(50, 130, n).round(1),
        "wind_speed":  np.random.uniform(1.5, 9.0, n).round(2),
    })


df, source_name = load_csv_data()
using_fallback = df is None or df.empty

if using_fallback:
    df = generate_fallback_data()
    data_source = "synthetic preview"
else:
    data_source = source_name

df.columns = [c.lower() for c in df.columns]
if "timestamp" in df.columns:
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    df = df.sort_values("timestamp").reset_index(drop=True)


# ---------------------------------------------------------------------------
# Forecast loading
# ---------------------------------------------------------------------------

@st.cache_data(ttl=3600, show_spinner=False)
def load_forecast():
    """
    Attempts to load forecast from the Hopsworks-backed inference module.
    Falls back to a simple linear extrapolation if the model is not available.
    """
    try:
        import sys
        sys.path.insert(0, str(project_root))
        from inference.predict import predict
        return predict(), "model"
    except Exception as e:
        return None, str(e)


# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------

with st.sidebar:
    st.markdown("### AQI Forecast")
    st.markdown('<p class="section-label">Configuration</p>', unsafe_allow_html=True)

    city_name    = st.text_input("City", value="Karachi")
    display_rows = st.slider("Historical records to show", 24, 120, 48)

    st.markdown("---")
    st.markdown('<p class="section-label">Data source</p>', unsafe_allow_html=True)
    st.caption(data_source)

    load_live_forecast = st.toggle("Load live forecast from model", value=True)

    st.markdown("---")
    st.markdown('<p class="section-label">Last updated</p>', unsafe_allow_html=True)
    st.caption(datetime.now().strftime("%Y-%m-%d  %H:%M"))

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------

latest     = df.iloc[-1]
current_aqi = float(latest.get("aqi", 0) or 0)
aqi_label, aqi_color = classify_aqi(current_aqi)

st.markdown(f"## {city_name} — Air Quality Dashboard")
st.markdown(
    f'<span class="aqi-badge" style="background:{aqi_color}20;color:{aqi_color};'
    f'border:1px solid {aqi_color}40">{aqi_label}</span>',
    unsafe_allow_html=True,
)
st.markdown("---")

# ---------------------------------------------------------------------------
# Current conditions
# ---------------------------------------------------------------------------

st.markdown('<p class="section-label">Current conditions</p>', unsafe_allow_html=True)

metric_defs = [
    ("AQI",         "aqi",         ""),
    ("PM2.5",       "pm25",        "ug/m3"),
    ("Temperature", "temperature", "C"),
    ("Humidity",    "humidity",    "%"),
    ("Wind Speed",  "wind_speed",  "m/s"),
]
cols = st.columns(len(metric_defs))
for col, (label, key, unit) in zip(cols, metric_defs):
    val = latest.get(key)
    try:
        display = f"{float(val):.1f} {unit}".strip()
    except (TypeError, ValueError):
        display = "N/A"
    col.metric(label, display)

st.markdown("---")

# ---------------------------------------------------------------------------
# 3-Day Forecast Section
# ---------------------------------------------------------------------------

st.markdown('<p class="section-label">3-day AQI forecast</p>', unsafe_allow_html=True)

forecast_data = None
forecast_source = "fallback"

if load_live_forecast:
    with st.spinner("Loading forecast from model..."):
        forecast_data, err = load_forecast()
        if forecast_data:
            forecast_source = "model"
        else:
            st.caption(f"Model unavailable ({err}). Showing trend-based estimate.")

# Fallback: simple extrapolation from recent AQI trend
if forecast_data is None:
    recent_aqi = df["aqi"].dropna().tail(24).values
    drift = float(np.mean(np.diff(recent_aqi[-6:]))) if len(recent_aqi) >= 6 else 0
    forecast_data = {
        "current_aqi":  current_aqi,
        "aqi_next_24h": round(np.clip(current_aqi + drift * 24, 0, 500), 1),
        "aqi_next_48h": round(np.clip(current_aqi + drift * 48, 0, 500), 1),
        "aqi_next_72h": round(np.clip(current_aqi + drift * 72, 0, 500), 1),
        "model_type":   "trend extrapolation",
    }
    forecast_source = "fallback"

# Forecast cards
horizons = [
    ("Now",     "current_aqi"),
    ("24 hours","aqi_next_24h"),
    ("48 hours","aqi_next_48h"),
    ("72 hours","aqi_next_72h"),
]

card_cols = st.columns(4)
for col, (horizon_label, key) in zip(card_cols, horizons):
    val = forecast_data.get(key, 0)
    label, color = classify_aqi(val)
    col.markdown(
        f"""
        <div class="forecast-card">
            <div class="forecast-label">{horizon_label}</div>
            <div class="forecast-value" style="color:{color}">{val:.0f}</div>
            <div class="forecast-category" style="color:{color}80">{label}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

st.markdown("<br>", unsafe_allow_html=True)

# Forecast line chart
now = datetime.now()
forecast_times = [now, now + timedelta(hours=24), now + timedelta(hours=48), now + timedelta(hours=72)]
forecast_values = [
    forecast_data["current_aqi"],
    forecast_data["aqi_next_24h"],
    forecast_data["aqi_next_48h"],
    forecast_data["aqi_next_72h"],
]

# Historical tail + forecast joined
hist_times  = df["timestamp"].tail(display_rows).tolist() if "timestamp" in df.columns else []
hist_values = df["aqi"].tail(display_rows).tolist()

fig_forecast = go.Figure()

# Historical line
fig_forecast.add_trace(go.Scatter(
    x=hist_times,
    y=hist_values,
    mode="lines",
    name="Historical AQI",
    line=dict(color="#38bdf8", width=1.6),
    fill="tozeroy",
    fillcolor="rgba(56,189,248,0.05)",
))

# Forecast line
fig_forecast.add_trace(go.Scatter(
    x=forecast_times,
    y=forecast_values,
    mode="lines+markers",
    name=f"Forecast ({forecast_data.get('model_type','').upper()})",
    line=dict(color="#f97316", width=2, dash="dot"),
    marker=dict(size=8, color="#f97316", line=dict(color="#0d0f14", width=2)),
))

# AQI threshold bands
for level, color, label in [
    (100, "#eab308", "Moderate"),
    (150, "#f97316", "Unhealthy for SG"),
    (200, "#ef4444", "Unhealthy"),
]:
    fig_forecast.add_hline(
        y=level, line_dash="dot", line_color=color, opacity=0.4,
        annotation_text=label,
        annotation_font=dict(size=9, color=color),
    )

# Vertical line at "now"
fig_forecast.add_vline(
    x=now.isoformat(),
    line_dash="solid",
    line_color="#475569",
    line_width=1,
    annotation_text="Now",
    annotation_font=dict(size=9, color="#475569"),
)

fig_forecast.update_layout(
    **PLOT_LAYOUT,
    title=dict(text="AQI — Historical + 3-Day Forecast", font=dict(size=12, color="#94a3b8")),
    legend=dict(bgcolor="rgba(0,0,0,0)", font=dict(size=10)),
    xaxis=dict(**PLOT_LAYOUT["xaxis"], title=""),
    yaxis=dict(**PLOT_LAYOUT["yaxis"], title="AQI"),
)
st.plotly_chart(fig_forecast, use_container_width=True)

if forecast_source == "model":
    st.caption(f"Forecast generated by {forecast_data.get('model_type','')} model from Hopsworks Model Registry.")
else:
    st.caption("Forecast is a trend-based estimate. Train the model and connect Hopsworks for ML predictions.")

st.markdown("---")

# ---------------------------------------------------------------------------
# Historical weather metrics
# ---------------------------------------------------------------------------

recent = df.tail(display_rows)

st.markdown('<p class="section-label">Meteorological data</p>', unsafe_allow_html=True)
col1, col2 = st.columns(2)

def make_line_chart(df_plot, y_col, title, color):
    fig = go.Figure()
    x = df_plot["timestamp"] if "timestamp" in df_plot.columns else df_plot.index
    fig.add_trace(go.Scatter(
        x=x, y=df_plot[y_col],
        mode="lines",
        line=dict(color=color, width=1.6),
        fill="tozeroy",
        fillcolor=f"{color}0d",
        name=y_col,
    ))
    fig.update_layout(**PLOT_LAYOUT, title=dict(text=title, font=dict(size=12, color="#94a3b8")))
    return fig

temp_col = next((c for c in recent.columns if c in ["temperature", "temp"]), None)
hum_col  = next((c for c in recent.columns if c in ["humidity", "hum"]),  None)

with col1:
    if temp_col:
        st.plotly_chart(make_line_chart(recent, temp_col, "Temperature (C)", "#fb923c"), use_container_width=True)

with col2:
    if hum_col:
        st.plotly_chart(make_line_chart(recent, hum_col, "Relative Humidity (%)", "#818cf8"), use_container_width=True)

# ---------------------------------------------------------------------------
# Pollutant breakdown
# ---------------------------------------------------------------------------

pollutant_cols = [c for c in ["pm25", "pm10", "o3", "no2", "so2", "co"] if c in recent.columns]

if pollutant_cols:
    st.markdown("---")
    st.markdown('<p class="section-label">Pollutant breakdown</p>', unsafe_allow_html=True)
    colors = ["#38bdf8", "#818cf8", "#fb923c", "#f472b6", "#34d399", "#facc15"]
    fig_poll = go.Figure()
    x = recent["timestamp"] if "timestamp" in recent.columns else recent.index
    for col, color in zip(pollutant_cols, colors):
        fig_poll.add_trace(go.Scatter(
            x=x, y=recent[col], mode="lines",
            name=col.upper(), line=dict(color=color, width=1.4),
        ))
    fig_poll.update_layout(
        **PLOT_LAYOUT,
        title=dict(text="Pollutant Levels (ug/m3)", font=dict(size=12, color="#94a3b8")),
        legend=dict(bgcolor="rgba(0,0,0,0)", font=dict(size=10)),
    )
    st.plotly_chart(fig_poll, use_container_width=True)

# ---------------------------------------------------------------------------
# Raw data table
# ---------------------------------------------------------------------------

st.markdown("---")
with st.expander("View raw data"):
    display_df = recent.copy()
    if "timestamp" in display_df.columns:
        display_df["timestamp"] = display_df["timestamp"].dt.strftime("%Y-%m-%d %H:%M")
    st.dataframe(display_df.tail(20), use_container_width=True, hide_index=True)